Spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=library
    username: postgres
    password: 123456

  shell:
    script:
      enabled: true
    interactive:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: false
#    generate-ddl: true
    hibernate:
      ddl-auto: none
#      ddl-auto: create-drop

  sql:
    init:
      mode: always
      schema-locations: schema.sql
      data-locations: data.sql
