spring:
  application:
    name: ${SERVICE_NAME:2024-11-otus-spring-kochetkova}
  messages:
    basename: i18n.messages
  jackson:
    locale: ru
question:
  filename: ${QUESTION_FILENAME:questions.csv}
  splitter: ${QUESTION_SPLITTER:;}