spring:
  application:
    name: ${SERVICE_NAME:2024-11-otus-spring-kochetkova}
  messages:
    basename: i18n.messages
  jackson:
    locale: ${LOCALE:en}
question:
  basefilename: question.questions
  splitter: ${QUESTION_SPLITTER:;}